check form submit and to empty fileList
BoomTech-LLC/BoomForm-Builder pull request #71
Opened 2023-02-02 14:07 UTC by AmramAnanyan

2023-02-06 07:23 UTC, Tiko-Nazaryan commented
Hey. 

First of all. You need to remove is Submitted state.
After you need to keep files in fields component using field_id. 
Set files data to boomform in files component where are located files state.

2023-02-06 07:24 UTC, Tiko-Nazaryan requested changes

2023-02-06 07:24 UTC, Tiko-Nazaryan commented on src/Body/Fields/File/File.js
> +import { Context, Input, useField } from 'boomform'
No need for context

2023-02-06 07:24 UTC, Tiko-Nazaryan commented on src/Body/Fields/File/File.js
> +  }, [isSubmited])
Use prettier.

2023-02-08 07:27 UTC, Tiko-Nazaryan requested changes

2023-02-08 07:27 UTC, Tiko-Nazaryan commented on src/Footer/SubmitButton/SubmitButton.js
> +        e.preventDefault()
Return this guy to his place

2023-02-08 07:27 UTC, Tiko-Nazaryan commented on src/Body/Fields.js
> +
try to remove this if everything is same keep it removed

2023-02-08 07:27 UTC, Tiko-Nazaryan commented on src/Body/Fields.js
> +        fileList[field.id] = null
Directly changed state

2023-02-08 07:27 UTC, Tiko-Nazaryan commented on src/Body/Fields/File/Preview.js
> +  // }
Move this to handlers

2023-02-08 07:27 UTC, Tiko-Nazaryan commented on src/Body/Fields/File/File.js
> +        if (key == id) {
Should be ===

2023-02-08 07:27 UTC, Tiko-Nazaryan commented on src/Body/Fields/File/File.js
> +      for (let key in prev) {
Useles loop. you can just take prev[id]. And write a condition if it's exists or not if not just create one

2023-02-08 07:27 UTC, Tiko-Nazaryan commented on src/Body/Fields/File/File.js
> +            prev[key]=[...prev[key],...newFiles]
Need to clone state before working with him

2023-02-08 07:27 UTC, Tiko-Nazaryan commented on src/Body/Fields/File/File.js
> +
Please use prettier

2023-02-08 07:27 UTC, Tiko-Nazaryan commented on src/Body/Fields/File/File.js
> +        }
If we are using only percentage === 0 which is start uploading and percentage === 100 which is file successfully uploaded. Why we don't use acceptFiles function which is file started to upload and  handleCallback which is file finished uploading ?

2023-02-08 07:27 UTC, Tiko-Nazaryan commented on src/Body/Fields/File/File.js
> +    ABORT_REQUEST_CONTROLLERS.get(fileId)?.abort()
Use ref for this.

2023-02-10 08:11 UTC, Tiko-Nazaryan approved these changes

2023-02-10 08:11 UTC, Tiko-Nazaryan commented on src/Body/Fields/File/File.js
> +          if (file.id === fileId) {
Distract state before assign something to him

2023-02-10 08:11 UTC, Tiko-Nazaryan commented on src/Body/Fields/File/List.js
> +    console.log(file)
Clarify with @sahak-sahakyan is this console needed in production

2023-02-10 12:35 UTC, Tigran0199 commented on src/Body/Fields/File/File.js
> +            }
Hors arev👌

2023-02-10 12:35 UTC, Tigran0199 approved these changes

2023-02-10 15:49 UTC, sahak-sahakyan commented
Chee vapshe needed chi

On Fri, Feb 10, 2023 at 12:12 PM Tiko-Nazaryan ***@***.***>
wrote:

> ***@***.**** approved this pull request.
> ------------------------------
>
> In src/Body/Fields/File/File.js
> <https://github.com/BoomTech-LLC/BoomForm-Builder/pull/71#discussion_r1102407943>
> :
>
> >      if (status === 200) {
> -      setFileList((prev) => prev.map((file) => {
> -        if (fileId === file.id) file.responce = responce
> -        return file
> -      }))
> +      setFileList((prev) => {
> +        const fileResponce = prev[id].map((file) => {
> +          if (file.id === fileId) {
>
> Distract state before assign something to him
> ------------------------------
>
> In src/Body/Fields/File/List.js
> <https://github.com/BoomTech-LLC/BoomForm-Builder/pull/71#discussion_r1102413114>
> :
>
> >    return value.map((file) => {
> -    const { id, type, percentage, size, originalName } = file
> -    console.log(file);
> +    const { id, type, size, originalName } = file
> +    console.log(file)
>
> Clarify with @sahak-sahakyan <https://github.com/sahak-sahakyan> is this
> console needed in production
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/BoomTech-LLC/BoomForm-Builder/pull/71#pullrequestreview-1292595768>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ATRNXXH4MB5AQ7X2LQF5OLTWWXZ5XANCNFSM6AAAAAAUPCJBU4>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2023-05-25 12:41 UTC, closed without merging